### ISSUE TITLE
Coral disease data into grafana plugin

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/grafana-dashboards#1]
How best to get the FWC coral disease data (presence/absence) in to the new dashboard? 

Picture files with dots of different colors?
Some way to add points to NetCDF files in ERDDAP?
Other ideas?

How to make a time series of spatial extent of disease?

**Comment by 7yl4r** [comment]
There are several grafana plugins that can help us display the data nicely, but we need to figure out the backend first. 
I am waiting to hear back from FWC's data guru Christi Santi on which backend they prefer; there are several workable options and I can help set one up once I know how the data is currently formatted.
