### ISSUE TITLE
FK /srv/imars-objects/fk static images missing

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/grafana-dashboards#10]

**Comment by 7yl4r** [comment]
autofs had frozen up on imars-webserver01.
When trying to `ls /srv/imars-objects/` the shell went unresponsive.

Fix:
```
[root@imars-webserver-01 ~]# systemctl restart autofs
```

**Comment by 7yl4r** [comment]
@dotis : grafana dashboard images are back up

**Comment by 7yl4r** [comment]
Happened again today

**Comment by 7yl4r** [comment]
i guess let's start a table

date noticed | context
-----------------|--------------------
2020-09-11 | storm last night

**Comment by dotis** [comment]
Ok. It must have been the storm. When I went in to check my desktop, it had turned off and needed a restart. Thanks.
________________________________

**Comment by 7yl4r** [comment]
imars-webserver01 is dead (was on dune before crash) and the dashboard in question is no longer in use so I'm closing this.
