### ISSUE TITLE
Directories for 7-day mean images on new dashboards

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/grafana-dashboards#2]
The directories where the 7day mean satellite images (netcdf) live have changed. The new structure is below. VIIRS has been added. The first region to change is FK. FGB will be ready soon. These directories will replace those for the FGBNMS and FKNMS dashboards as well. We will now have three boards: FWC, FKNMS and FGBNMS. 

MODIS-Aqua (MODA) 
/srv/imars-objects/fk/MEAN_7D_MODA/OC
/srv/imars-objects/fk/MEAN_7D_MODA/SST
/srv/imars-objects/fk/MEAN_7D_MODA/SST4

VIIRS-SNPP (VSNPP)
/srv/imars-objects/fk/MEAN_7D_VSNPP/OC
/srv/imars-objects/fk/MEAN_7D_VSNPP/SST
/srv/imars-objects/fk/MEAN_7D_VSNPP/SSTN

Now that we have added VIIRS, we have some choices in terms of products. VIIRS is more recent and should last longer into the future. It also has a bit better resolution at 750m. For the FWC board, let's do this:
chlor_a (VSNPP)
SST (VSNPP)
ABI (MODA - VIIRS has no fluorescence band, could try to use S3)
Rrs_671 (VSNPP)

These will update once a week on Wednesdays. This structure is very similar to the current boards, but all files are now on /srv. We can still think about airflow here and adding Sentinel-3. For now, let's get the FWC board up with the products above.

**Comment by 7yl4r** [comment]
I've added all I can but `/srv/imars-objects/fk/MEAN_7D_MODA/SST4` is empty; I can't add it to ERDDAP until there is some data there.

**Comment by dotis** [comment]
Ok. Those are populating now. Should take 1-2 hours.

**Comment by dotis** [comment]
The MEAN_7D directories for FK should be fully populated now for MODA and VSNPP.

**Comment by dotis** [comment]
These all look fine and are updated, except for the MODIS ABI and the VIIRS Kd490.

**Comment by 7yl4r** [comment]
@dotis : Where is the VIIRS Kd490 data?
I looked in `/srv/imars-objects/fk/MEAN_7D_VSNPP/OC` for Prod name="Kd_490_median" but I don't see it there.

**Comment by dotis** [comment]
Hmm. I'm looking at one of those files now and Kd_490_median is there. The OC files have six prods:

chlor_a_median
chlor_a_anom
Rrs_671_median
Rrs_671_anom
Kd_490_median
Kd_490_anom
________________________________

**Comment by 7yl4r** [comment]
Ok. There must be something missing in my ERDDAP setup.
