### ISSUE TITLE
6 years of coral disease yes/no panel

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/grafana-dashboards#5]
Filled circles on each site for where coral disease detected, empty circles where it has not.

**Comment by dotis** [comment]
I can do this manually for now. I will make static annual maps that we can put in a panel. I still don't have any coral disease data for 2018-2020. Have you seen any more recent data?

**Comment by 7yl4r** [comment]
No, it sounds like the data format isn't fully settled yet so they haven't put all the data together yet.

**Comment by dotis** [comment]
Ok. Well, I'll do four maps then. 2014-2017
