### ISSUE TITLE
+ another river discharge panel

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/grafana-dashboards#6]
for east coast rivers

**Comment by dotis** [comment]
I am almost done with this. This will be another csv file with "EFL" in the filename. I'll send the path once I check the data. We will have two panels; the existing one for Everglades rivers and one for the new EFL rivers.

**Comment by dotis** [comment]
River discharge csv are now here:
E Florida rivers:
/srv/imars-objects/fk/DISCH_CSV_USGS/USGS_disch_FWCdb_EFL.csv
W FL rivers:
/srv/imars-objects/fk/DISCH_CSV_USGS/USGS_disch_FKdb.csv

**Comment by 7yl4r** [comment]
river discharge ingests added: https://github.com/USF-IMARS/imars_dags/commit/29c4a424f720488f33dbda25b6940c443f0032aa

**Comment by 7yl4r** [comment]
@dotis : I have just added the data from the rivers to the dash but the "East" rivers data has values no greater than 2. Is there something off in the calculation?

**Comment by dotis** [comment]
No. Those are actually gage height measurements, which is what is measured. Those numbers are in line with what I saw when I did a rough plot of the data. I'm adding panels now for the annual disease maps. Are you about done with your edits? I don't want to cause a conflict.
________________________________

**Comment by 7yl4r** [comment]
Yeah I'm done editing them for the day.

**Comment by dotis** [comment]
I added the maps. Is there a way we can get them to expand in another tab if a user clicks on them (like the sat. images)? Also, I selected "Add panel" on the cumulative % panel you added and it added the new map panels to that row. I guess I need to add a new row instead. What's the best way to do that?

**Comment by 7yl4r** [comment]
Adding a new row is all the way down at the bottom and then you need to move it up to where you want it. 

I don't think there is an easy way to make the images clickable in markdown. 
We would probably need to use html instead of markdown.
Something like 

```html
<a href="img_path.png"><img src="img_path.png"></img></a>
```

**Comment by dotis** [comment]
Is there a way to add HTML in Grafana? When I edit in the text panel, it says HTML is not supported, only markdown. It's not a huge deal. It's just a little hard to see any detail in the maps when they are in the panel.

**Comment by 7yl4r** [comment]
There is a "mode" dropdown under options where you can select markdown or html

**Comment by dotis** [comment]
Got it. Thanks.

**Comment by dotis** [comment]
The buoy data (FKNMS and FWC only) is now being generated in two locations:
Old: /srv/imars-objects/modis_aqua_fk/SAL_TS_NDBC
New: /srv/imars-objects/fk/SAL_TS_NDBC/

There are identical files in each location and both are updated nightly. My goal is to get rid of the "modis_aqua_fk" directory at some point. For now, either one will work, so we can leave this alone for now.

**Comment by 7yl4r** [comment]
I've opened a new issue [here](https://github.com/USF-IMARS/imars_dags/issues/99) to help me track this bouy location update. 
I'll come back to it a while after we demo with the FWC folks.
