### ISSUE TITLE
+ new timeseries to 

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/grafana-dashboards#8]
This could be set up as a cronjob so that it can be included in the dockerized future version.
For now we could add it to [the similar airflow DAG here](https://github.com/USF-IMARS/imars_dags/tree/master/imars_dags/dags/csvs_to_graphite).

-----------------------

Information for FWC dashboard:

    Extracted time-series are in csv files, very similar to older versions:
    7 Locations for extracted data on FWC board (ID appears in filenames):
    SLI, PBI, PEV, MIA, MOL, SOM, KW

Using RoI "PEV" as an example:

Product: SSTN(VIIRS)
Directory w/example file:
/srv/imars-objects/fk/EXT_TS_VSNPP/SSTN/FKdbv2_sstn_TS_VSNPP_daily_PEV.csv

Product: chlor_a (VIIRS)
Directory w/example file:
/srv/imars-objects/fk/EXT_TS_VSNPP/OC/FKdbv2_chlor_a_TS_VSNPP_daily_PEV.csv

Product: Rrs_671 (VIIRS)
Directory w/example file:
/srv/imars-objects/fk/EXT_TS_VSNPP/OC/FKdbv2_Rrs_671_TS_VSNPP_daily_PEV.csv

Product: Kd_490 (VIIRS)
Directory w/example file:
/srv/imars-objects/fk/EXT_TS_VSNPP/OC/FKdbv2_Kd_490_TS_VSNPP_daily_PEV.csv

Product: ABI (MODA)
Directory w/example file:
/srv/imars-objects/fk/EXT_TS_MODA/OC/FKdbv2_ABI_TS_MODA_daily_PEV.csv

**Comment by 7yl4r** [comment]
Implemented ingest in [imars_dags:fwc_sat_region.py](https://github.com/USF-IMARS/imars_dags/blob/master/imars_dags/dags/csvs_to_graphite/py_scripts/fwc_sat_region.py)

**Comment by 7yl4r** [comment]
@dotis : I would like to rename these:

```
# old names:
/srv/imars-objects/fk/EXT_TS_VSNPP/SSTN/FKdbv2...

# new names:
/srv/imars-objects/fk/EXT_TS_VSNPP/SSTN/FWCdbv2...
```

This is to keep things consistent within our database.
Putting them under `FK` would cause FWC & FK stations data to be all mixed up.

**Comment by dotis** [comment]
Ok.

________________________________

**Comment by dotis** [comment]
I'll need to change my code a bit to feed into those. The images for FK and FWC should be the same, but the extent is the only difference.

**Comment by 7yl4r** [comment]
Ok. I've just renamed them so they can get picked up by the airflow job and put into the database.
This change is just for the csv files.

**Comment by dotis** [comment]
These files actually encompass locations that will be used for both dashboards. I simply added new locations to the previous list of FK locations, only a handful of which are actually displayed. Do you want me to add a "FK" prefix to the FK ones and "FWC" for the FWC locations? Currently I see locations for the FKNMS board with an "FWC" prefix.

**Comment by dotis** [comment]
I should add that updated versions of these files are created each day, with old files being written over with new data tacked on the end.

**Comment by 7yl4r** [comment]
Oh. If the locations for the FK and FWC boards are the same then we can put them all together.
I split FWC out from FK because I didn't realize there was overlap between the FK and FWC sites.
Let's put them all together under FK and I'll update my scripts

**Comment by dotis** [comment]
Well, each board has its own set of locations and there is no overlap. But it is just one big set of files that has the locations for each board. I may have been unclear. Here is the breakdown:

FWC: SLI, PBI, PEV, MIA, MOL, SOM, KW (and they may want to add more)

FKNMS: BIS, UK, MUK, MK, LK, MQ, DT, WFB, EFB, WFS, SR

These location names are at the tail end of each filename. All the location names are unique. Let me know if I should make changes.

**Comment by 7yl4r** [comment]
Ok. I've added these lists to the templating query.
All timeseries will fall under the same graphite namespace (`imars_regions.fk.roi.*`) and the grafana selector includes this subset.
This means that adding and removing stations for both dashboards is handled within the grafana user interface.
This will be much easier than managing different namespaces in graphite.

The ingest for all of these regions is handled in [imars_dags/.../fwc_sat_region.py](https://github.com/USF-IMARS/imars_dags/blob/master/imars_dags/dags/csvs_to_graphite/py_scripts/fwc_sat_region.py)

I'll close this once I get a successful run from airflow.
