### ISSUE TITLE
Change limits and color scale for new VIIRS images

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/grafana-dashboards#9]
Here are the limits that we used for the FKNMS board. Let's start with these for the new VIIRS images on the FWC board.
Chlor_a_anom: -1 to +1 (colormap = jet); not sure if ERDDAP uses "jet", but it goes from purple to bright red. Zero is represented by green. Maybe this called "Rainbow"

SST anom: -3 to +3 (colormap = ?); not sure the name of the colormap, but it goes from blue to red. Zero is represented by white. Maybe this is called "BlueWhiteRed"

ABI anom: -0.2 to +0.2; purple to red colormap. 0=green.

Rrs_671 anom: =0.005 to +0.005; purple to red colormap. 0=green.

Kd_490 anom: Not sure of this just yet. Let's start with -0.5 to +0.5; purple to red colormap. 0=green.

I forget the link to change these. I'm happy to play with these if you send me the link to ERDDAP graph tool.

**Comment by 7yl4r** [comment]
I've updated chlor a and sst on the dash and will do the others when they are up.
Here are the format strings for each:

* [x] chlor a :  Rainbow|||-1|1|
* [x] sst        : BlueWhiteRed|||-3|3|
* [x] abi       : Rainbow|||-0.2|0.2|
* [x] Rrs_671 : Rainbow|||-0.005|0.005|
* [x] Kd_490  : Rainbow|||-0.5|0.5|
